### ISSUE TITLE
Links to the improvement commits

### ISSUE THREAD

**Issue by paradise1260** [UBC-MDS-2021-22/vancouver_crime_dashboard#74]
- A collapse button including the usage of filters: https://github.com/UBC-MDS/vancouver_crime_dashboard/commit/7ced53a81792933770c6bf2f2479f01737f586e9

**Comment by mmaidana24318** [comment]
* Update map from circles to choropleth: [12ceca3](https://github.com/UBC-MDS/vancouver_crime_dashboard/pull/76/commits/12ceca305f80f3f381cf22f524f96550f3ad6f25)

**Comment by mmaidana24318** [comment]
(Cici) changed neighbourhood filter and added dashboard description [b64249d](https://github.com/UBC-MDS/vancouver_crime_dashboard/pull/68/commits/b64249dbca8f45d6dc73f4dc3b3c23e42e8ecaa3)

**Comment by mmaidana24318** [comment]
Updated icon and added attribution [417461d](https://github.com/UBC-MDS/vancouver_crime_dashboard/commit/417461d3336c95aff2d02226e374ddea890186b1)

**Comment by sy25wang** [comment]
Update bar chart to reflect only top 5 crimes based on the peer feedback [6cf26f8](https://github.com/UBC-MDS/vancouver_crime_dashboard/commit/6cf26f806a41270cf3c7e71cd82b70f74f7ef4e8)
